version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  millenium.cyrhades.fr:
    image: anssi/fcsc2022-crypto-millenium:latest
    ports:
      - ${PORT_SSH}:4000